include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/core/localization/generated/**

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    use_string_buffers: true
